# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir W:/ELEC3500/ELEC3500_LAB_9/EggTimer/EggTimer/EggTimer.cache/wt [current_project]
set_property parent.project_path W:/ELEC3500/ELEC3500_LAB_9/EggTimer/EggTimer/EggTimer.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo w:/ELEC3500/ELEC3500_LAB_9/EggTimer/EggTimer/EggTimer.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet w:/ELEC3500/ELEC3500_LAB_9/EggTimer/EggTimer/EggTimer.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files w:/ELEC3500/ELEC3500_LAB_9/EggTimer/EggTimer/EggTimer.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
add_files -quiet w:/ELEC3500/ELEC3500_LAB_9/EggTimer/EggTimer/EggTimer.srcs/sources_1/ip/c_counter_binary_db/c_counter_binary_db.dcp
set_property used_in_implementation false [get_files w:/ELEC3500/ELEC3500_LAB_9/EggTimer/EggTimer/EggTimer.srcs/sources_1/ip/c_counter_binary_db/c_counter_binary_db.dcp]
read_verilog -library xil_defaultlib {
  W:/ELEC3500/ELEC3500_LAB_9/EggTimer/EggTimer/EggTimer.srcs/sources_1/new/down_counter.v
  W:/ELEC3500/ELEC3500_LAB_9/EggTimer/EggTimer/EggTimer.srcs/sources_1/new/set_timer.v
  W:/ELEC3500/ELEC3500_LAB_9/EggTimer/EggTimer/EggTimer.srcs/sources_1/imports/new/clk_div.v
  W:/ELEC3500/ELEC3500_LAB_9/EggTimer/EggTimer/EggTimer.srcs/sources_1/new/count_time.v
  W:/ELEC3500/ELEC3500_LAB_9/EggTimer/EggTimer/EggTimer.srcs/sources_1/new/debounce.v
  W:/ELEC3500/ELEC3500_LAB_9/EggTimer/EggTimer/EggTimer.srcs/sources_1/imports/new/binary_to_BCD.v
  W:/ELEC3500/ELEC3500_LAB_9/EggTimer/EggTimer/EggTimer.srcs/sources_1/new/eggtimer.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc W:/ELEC3500/ELEC3500_LAB_9/EggTimer/EggTimer/EggTimer.srcs/constrs_1/imports/new/CONSTRAINT.xdc
set_property used_in_implementation false [get_files W:/ELEC3500/ELEC3500_LAB_9/EggTimer/EggTimer/EggTimer.srcs/constrs_1/imports/new/CONSTRAINT.xdc]


synth_design -top eggtimer -part xc7a100tcsg324-1


write_checkpoint -force -noxdef eggtimer.dcp

catch { report_utilization -file eggtimer_utilization_synth.rpt -pb eggtimer_utilization_synth.pb }
