# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: W:/ELEC3500/ELEC3500_LAB_9/EggTimer/EggTimer/EggTimer.srcs/sources_1/ip/c_counter_binary_db/c_counter_binary_db.xci
# IP: The module: 'c_counter_binary_db' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: w:/ELEC3500/ELEC3500_LAB_9/EggTimer/EggTimer/EggTimer.srcs/sources_1/ip/c_counter_binary_db/c_counter_binary_db_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_counter_binary_db'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: W:/ELEC3500/ELEC3500_LAB_9/EggTimer/EggTimer/EggTimer.srcs/sources_1/ip/c_counter_binary_db/c_counter_binary_db.xci
# IP: The module: 'c_counter_binary_db' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: w:/ELEC3500/ELEC3500_LAB_9/EggTimer/EggTimer/EggTimer.srcs/sources_1/ip/c_counter_binary_db/c_counter_binary_db_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_counter_binary_db'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
